box_name     = "chef12-playground"
chef_version = "12.5.1"
run_list     = ['store::default']

Vagrant.configure("2") do |c|
  c.vm.box = "ubuntu/trusty64"
  c.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/1/providers/virtualbox.box"
  c.vm.hostname = box_name
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.omnibus.chef_version = chef_version
  c.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = "../"
    run_list.each do |recipe|
      chef.add_recipe recipe
    end
  end
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "1024"]
    p.customize ["modifyvm", :id, "--cpus", "1"]
    p.customize ["modifyvm", :id, "--pae", "on"]
    p.customize ["modifyvm", :id, "--nestedpaging", "on"]
    p.customize ["modifyvm", :id, "--hwvirtex", "on"]
    p.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    p.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    p.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
  end
end
